### ISSUE TITLE
V-Slim Unknown html tag

### ISSUE THREAD

**Issue by TholthoeunChansovann** [paliari/v-slim-dialog#1]
Thank for share you cool package. With this package very easy to use,  but after i response with HTML tag it not work. How i can do this? Thank for help
![capture](https://user-images.githubusercontent.com/12667706/45006209-f1af3180-b021-11e8-91b8-29c598075fc0.JPG)

**Comment by akhoury** [comment]
it's because it's not using the `v-html` directive, i just submitted a PR https://github.com/paliari/v-slim-dialog/pull/2

**Comment by paliari** [comment]
The purpose of this component is to be lightweight, the name already says "v-slim-dialog".
Therefore we understand that this suggestion is not in accordance with the project.
You can customize the style by overwriting CSS casts.

**Comment by akhoury** [comment]
> The purpose of this component is to be lightweight, the name already says "v-slim-dialog".

Yea, sure, I understand, but this PR https://github.com/paliari/v-slim-dialog/pull/2 didn't increase the lines of code in the project, so it's still `slim` and all what Vue is doing under the hood is using `node.innerHTML = value`. I understand it's probably more code paths to test, but this project doesn't have any tests yet.

> You can customize the style by overwriting CSS casts.

How would you customize specific "words" in a sentence and change markup if you're outputting text nodes? 

I didn't want to publish my own version on npm to reduce the clutter in the registry, but I guess I have to now.

Anyways, thanks for considering it.

**Comment by akhoury** [comment]
Yea, see this live example https://codesandbox.io/s/9ynr4lmp5r which is using my fork's build

![screen shot 2018-09-19 at 9 48 05 am](https://user-images.githubusercontent.com/1398375/45735639-3970b400-bbf1-11e8-8d41-a6c89faf939e.png)

The `HelloWorld.vue` file content

![screen shot 2018-09-19 at 9 48 17 am](https://user-images.githubusercontent.com/1398375/45735649-48576680-bbf1-11e8-9a90-802c8bd60239.png)

**Comment by TholthoeunChansovann** [comment]
@akhoury for it me not working.
![capture](https://user-images.githubusercontent.com/12667706/45735980-dd6b5700-bc13-11e8-8ebf-926a81b4eb01.JPG)

**Comment by akhoury** [comment]
You have to use my for in your `package.json`

```json
 "dependencies": {
    "vue": "^2.5.2",
    "v-slim-dialog": "akhoury/v-slim-dialog"
  },
```
